Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-04, with the labels that each got.

#12 [Bug]: Color branding for login page not working
  src/Controller/Admin/IndexController.php
  src/Controller/Admin/LoginController.php
  src/Controller/Admin/MiscController.php
  templates/admin/index/index.html.twig
  templates/admin/login/layout.html.twig
  templates/admin/misc/admin_css.html.twig
Labels: Bug

#14 Fix: ace-editor
  public/assets/admin.js
  public/build/admin/835.css
  public/build/admin/admin.js
  public/build/admin/entrypoints.json
  public/build/admin/manifest.json
  public/build/admin/runtime.js
  public/build/imageEditor/imageEditor.js
Labels: Bug

#30 [Security] Fix Admin Translation Export SQL Injection
  src/Controller/Admin/TranslationController.php
Labels: Security

#25 [Security] Adapted xss fixes for date fields
  public/js/pimcore/object/classes/data/date.js
  public/js/pimcore/object/classes/data/datetime.js
Labels: Security

#27 [Security] Adopted sql injection fix for translation api
  src/Controller/Admin/TranslationController.php
Labels: Security

#20 [Task]: Remove System Settings from Admin Bundle
  config/services.yaml
  public/js/pimcore/settings/system.js
  public/js/pimcore/settings/systemAppearance.js
  src/Controller/Admin/IndexController.php
  src/Controller/Admin/SettingsController.php
  src/DependencyInjection/Configuration.php
  src/Event/AdminEvents.php
  src/Helper/SystemConfig.php
  src/System/AdminConfig.php
  src/System/Config.php
Labels: Task

#32 [Security] Adopt xss fix for login screen
  src/Controller/Admin/LoginController.php
Labels: Security

#31 [Security] Adopt xss fix for website settings
  public/js/pimcore/settings/website.js
Labels: Security

#26 [Security] Adopted xss fixes for quantity values panel
  public/js/pimcore/object/quantityvalue/unitsettings.js
Labels: Security

#13 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
  .github/ci/files/.my.cnf
  .github/ci/files/bin/console
  .github/ci/files/config/packages/security.yaml
  .github/ci/files/config/system.yml
  .github/ci/files/kernel/Kernel.php
  .github/ci/files/public/.htaccess
  .github/ci/files/public/index_test.php
  .github/ci/files/templates/.gitkeep
Labels: sync

#33 [Github Action] Setup phpstan
  .github/ci/scripts/setup-pimcore-environment.sh
  .github/workflows/static-analysis.yml
  composer.json
  phpstan-baseline.neon
  phpstan-bootstrap.php
  phpstan.neon
Labels: Task

#42 [Bug]: Admin throws SessionBagInterface "pimcore_admin" is not registered
  config/event_listeners.yaml
  src/EventListener/AdminConfigListener.php
Labels: Bug

#34 [Documents] Fix console error "personalization" on undefined
  public/js/pimcore/document/edit.js
Labels: Bug

#39 [Github Action] Setup codeception and add test from core.
  .github/ci/files/config/bundles.php
  .github/ci/files/config/config.yaml
  .github/ci/files/config/event_listeners.yaml
  .github/ci/files/config/export.yaml
  .github/ci/files/config/packages/test/config.yaml
  .github/ci/files/config/security_services.yaml
  .github/ci/files/config/serializer.yaml
  .github/ci/files/config/services.yaml
  .github/ci/files/config/system.yaml
  .github/workflows/codeception.yml
  .gitignore
  codeception.dist.yml
  composer.json
  tests/Model.suite.dist.yml
  tests/Model/GridHelper/GridHelperTest.php
  tests/Model/Permissions/ModelAssetPermissionsTest.php
  tests/Model/Permissions/ModelDataObjectPermissionsTest.php
  tests/Model/Permissions/ModelDocumentPermissionsTest.php
  tests/Readme.md
  tests/Support/Helper/Model.php
  tests/Support/Helper/Unit.php
  tests/Support/UnitTester.php
  tests/_bootstrap.php
  tests/bin/docker-compose.yml
  tests/bin/init-tests.sh
Labels: Task

#41 [Security] Fix Properties Parameter
  public/js/pimcore/document/editables/link.js
Labels: Security

#38 [Task] Add PHP CS Fixer
  .github/workflows/php-cs-fixer.yaml
  .gitignore
  .php-cs-fixer.dist.php
  .php_cs.dist
Labels: Task

#47 [Security] XSS in Classification Store of Data Objects module - follow-up.
  public/js/pimcore/object/classificationstore/collectionsPanel.js
  public/js/pimcore/object/classificationstore/groupsPanel.js
  public/js/pimcore/object/classificationstore/propertiesPanel.js
  src/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Security

#46 [Security] Stored cross site scripting vulnerability in Save grid option in pimcore dashboard
  public/js/pimcore/element/helpers/gridColumnConfig.js
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Security

#44 [Security] Admin Authenticated Arbitrary File Read
  public/js/pimcore/asset/tree.js
  src/Controller/Admin/Asset/AssetController.php
  translations/admin.en.yaml
Labels: Security

#48 Follow up of pimcore/pimcore#14953
  src/System/AdminConfig.php
Labels: Task

#36 [Task] Removed deprecated `attributes` field in link editable
  public/js/pimcore/document/editables/link.js
  public/js/pimcore/helpers.js
  translations/admin.en.yaml
Labels: Task

#45 [Security] Fixed xss in translations panel
  config/pimcore/default.yaml
  src/Controller/Admin/TranslationController.php
Labels: Security

#53 [Task] Add security listener only when service is defined
  config/logout_listener.yaml
  config/security_services.yaml
  src/DependencyInjection/PimcoreAdminExtension.php
Labels: Task

#52 [Security] Stored cross site scripting vulnerability in operator any getter in pimcore grid configuration
  public/js/pimcore/object/gridcolumn/operator/AnyGetter.js
  public/js/pimcore/settings/metadata/predefined.js
  src/Controller/Admin/Asset/AssetHelperController.php
  src/Controller/Admin/DataObject/DataObjectHelperController.php
  src/DataObject/GridColumnConfig/Operator/AbstractOperator.php
  src/DataObject/GridColumnConfig/Operator/AnyGetter.php
Labels: Security

#54 Fix targeting page preview and move bundle specific css
  public/css/icons.css
  public/js/pimcore/document/pages/preview.js
Labels: Bug

#50 [Pimcore 11][Bug]: PDF document version preview not working anymore
  src/Security/ContentSecurityPolicyHandler.php
Labels: Bug

#56 [Task] Add missing permission
  src/Installer.php
Labels: Task

#55 [Task] Restructure permissions layout
  public/js/pimcore/settings/user/user/settings.js
  src/Controller/Admin/UserController.php
Labels: Task
