Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-09, with the labels that each got.

#253 Fix: check if icon exists in custom view
  public/js/pimcore/startup.js
Labels: Bug

#263 Clear controller/template if you convert page to email/snippet
  src/Controller/Admin/Document/DocumentController.php
Labels: Bug

#244 Fix UI element permissions
  public/js/pimcore/asset/tree.js
  public/js/pimcore/document/tree.js
  public/js/pimcore/helpers.js
  public/js/pimcore/object/tree.js
  src/Controller/Admin/ElementControllerBase.php
Labels: Improvement

#212 [Events] Add event pimcore.events.postEditObjectKey fired after rename on data object
  public/js/pimcore/elementservice.js
  public/js/pimcore/events.js
Labels: Improvement

#256 [Bug]: Fix cannot addEventListener to null in unsupported browser
  templates/admin/login/login.html.twig
Labels: Bug

#264 [Bug]: Fix avoid recursion on replaced arguments having further %
  public/js/pimcore/functions.js
  public/js/pimcore/settings/translation.js
Labels: Bug

#261 Editor Tabbar: Fix bad hover contrast color
  public/css/admin.css
Labels: Bug

#262 Fix quicksearch: pimcore_user() only accept ints
  templates/searchadmin/search/quicksearch/info_table.html.twig
Labels: Bug

#266 Fix object rename not updating the tree store
  public/js/pimcore/elementservice.js
  public/js/pimcore/helpers.js
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/DataObject/DataObjectController.php
  src/Controller/Admin/Document/DocumentController.php
Labels: Bug

#241 Check if parent is not undefined before appending it as request param when uploading an asset
  public/js/pimcore/helpers.js
Labels: Bug

#115 Feature/add support for an in filter operator to grid helper
  public/js/pimcore/overrides.js
  src/Helper/GridHelperService.php
Labels: Improvement

#227 Fix HTML validation of login form
  templates/admin/login/layout.html.twig
  templates/admin/login/login.html.twig
Labels: Bug

#286 [Bug]: Fix old password not being empty when resetting
  src/Controller/Admin/UserController.php
Labels: Bug

#273 [Bug]: Fix versions reload should not trigger on failed save
  CHANGELOG.md
  public/js/pimcore/object/object.js
Labels: Improvement, Backlog

#287 require 11.x
  composer.json
Labels: Task

#283 [Documents] Image Editable - fix default upload path
  public/js/pimcore/document/editables/image.js
  src/Controller/Admin/IndexController.php
Labels: Bug

#249 Don't use legacy/internal Image::getThumbnailConfig() method
  src/Controller/Admin/Asset/AssetController.php
Labels: Task

#274 Use Maintenance Mode Helper
  src/Controller/Admin/IndexController.php
  src/Controller/Admin/MiscController.php
Labels: Improvement

#277 [Bug]: Fix icon of variant language not working on link/unlink documents
  public/js/pimcore/document/document.js
Labels: Bug

#285 [Improvement]: Check if new password is NOT the same as the old one when resetting
  CHANGELOG.md
  src/Controller/Admin/UserController.php
Labels: Improvement

#269 [Improvement]: Make Password Recovery Token to be one time use only
  CHANGELOG.md
  src/Controller/Admin/LoginController.php
  src/Controller/Admin/UserController.php
Labels: Improvement

#144 feature/globalaction-field-save-yaml-specified
  src/Controller/Admin/WorkflowController.php
Labels: Improvement

#267 [AdminStyle] Allow element text modification on tree
  src/Controller/Traits/AdminStyleTrait.php
Labels: Improvement

#288 [Events] add event pimcore.events.postBuildPerspectiveElementTree and…
  public/js/pimcore/events.js
  public/js/pimcore/startup.js
Labels: Improvement

#238 Clean test environment
  .github/ci/files/.env
  .github/ci/scripts/setup-pimcore-environment.sh
  .gitignore
  composer.json
Labels: Task

#293 Remove redundant layout expansions in GRID config
  public/js/pimcore/object/helpers/classTree.js
Labels: Bug

#300 Remove redundant layout expansions in GRID config
  public/js/pimcore/object/helpers/classTree.js
Labels: Bug

#299 Follow up to #144
  src/Controller/Admin/WorkflowController.php
Labels: Task

#231 feat: preselect the site based on the current host
  src/Service/PreviewGenerator.php
Labels: Improvement

#297 Added support for import/export quantity value unit definition
  public/js/pimcore/object/quantityvalue/unitsettings.js
  src/Controller/Admin/DataObject/QuantityValueController.php
Labels: New Feature

#225 Adding a filter for the path column in the dependencies view
  public/js/pimcore/element/dependencies.js
  src/Controller/Admin/ElementController.php
Labels: Improvement
