Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-10, with the labels that each got.

#291 [Feature]: Manage Select options Via interface
  public/css/icons.css
  public/js/pimcore/layout/toolbar.js
  public/js/pimcore/object/classes/data/multiselect.js
  public/js/pimcore/object/classes/data/select.js
  public/js/pimcore/object/helpers/grid.js
  public/js/pimcore/object/helpers/reservedWords.js
  public/js/pimcore/object/helpers/selectField.js
  public/js/pimcore/object/selectoptions.js
  public/js/pimcore/object/selectoptionsitems/definition.js
  public/js/pimcore/object/tags/select.js
  src/Controller/Admin/DataObject/ClassController.php
  src/Controller/Admin/IndexController.php
  src/Event/AdminEvents.php
  templates/admin/index/index.html.twig
  translations/admin.en.yaml
  translations/admin_ext.en.yaml
Labels: New Feature

#301 [Improvement]: Add sanitizing pdf
  src/Controller/Admin/Asset/AssetController.php
  templates/admin/asset/get_preview_pdf_in_progress.html.twig
  templates/admin/asset/get_preview_pdf_unsafe.html.twig
  templates/admin/asset/show_version_document.html.twig
  translations/admin.en.yaml
Labels: Improvement

#290 [Reverse relation] Support configuration of visible fields
  public/js/pimcore/object/classes/data/reverseObjectRelation.js
  public/js/pimcore/object/tags/manyToManyObjectRelation.js
  public/js/pimcore/object/tags/reverseObjectRelation.js
Labels: Improvement

#306 [DataObject][MultiSelect] Fix options provider UI
  public/js/pimcore/object/classes/data/multiselect.js
Labels: Bug

#307 [Improvement]: Add post edit events
  public/js/pimcore/elementservice.js
  public/js/pimcore/events.js
Labels: Improvement

#308 [Bug]: Allow non-admin users to delete their profile picture
  src/Controller/Admin/UserController.php
Labels: Bug

#312 POEditor translations import
  translations/admin.hu.yaml
  translations/admin.uk.yaml
  translations/admin_ext.hu.yaml
  translations/admin_ext.ro.yaml
Labels: Task

#309 Revert "[Security] Fixed xss in translations panel" & "Translations transforms special characters"
  public/js/pimcore/settings/translation.js
  src/Controller/Admin/TranslationController.php
Labels: Bug

#311 [Bug]: WYSIWYG Editable is not empty when no content is added
  public/js/pimcore/document/edit.js
  public/js/pimcore/object/edit.js
Labels: Bug

#315 Fix: more generic check for empty wysiwyg
  public/js/pimcore/document/edit.js
  public/js/pimcore/object/edit.js
  public/js/pimcore/settings/translationEditor.js
Labels: Bug

#317 Add Missing Translations
  translations/admin.en.yaml
Labels: Bug
