Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-05, with the labels that each got.

#58 Made CSP alias public
  config/security_services.yaml
Labels: Bug

#10 Remove AdminAuthenticationDoubleCheckListener related stuff
  config/pimcore/default.yaml
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/PimcoreAdminExtension.php
  tests/Support/Helper/Unit.php
Labels: Task

#59 Remove deprecated code and make scriptProxyAction() as internal
  src/Controller/Admin/MiscController.php
Labels: Task

#61 Removed bundle specific css
  public/css/adminer-modifications.css
  public/css/print/print-printermarks.css
  public/css/reports.css
  public/css/word-export.css
Labels: Task

#62 [Bug] Open the SEO Document Editor dose not work.
  src/Controller/Traits/DocumentTreeConfigTrait.php
Labels: Bug

#64 [Task]: Remove Button control for DataObjects
  public/js/pimcore/object/classes/layout/button.js
Labels: Task

#65 [Github Action] Setup PO editor sync
  .github/workflows/poeditor-export.yaml
Labels: Improvement

#15 [Asset] Remove import from URL
  public/js/pimcore/asset/tree.js
  src/Controller/Admin/Asset/AssetController.php
  translations/admin.en.yaml
Labels: Task

#67 [Bug]: Remove button.js from templates
  templates/admin/index/index.html.twig
Labels: Bug

#69 [Events] Trigger Login Redirect event on login page not on authentication
  src/Controller/Admin/LoginController.php
Labels: Bug

#70 [Bug]: Trimmer operator value error
  src/DataObject/GridColumnConfig/Operator/Trimmer.php
Labels: Bug

#71 [Task] Remove columnType selection for daterange
  public/js/pimcore/object/classes/data/dateRange.js
Labels: Bug

#68 load first page in search
  public/js/pimcore/settings/website.js
Labels: Bug

#73 [Bug] Unable to download image in Custom download
  src/Controller/Admin/Asset/AssetController.php
Labels: Bug

#72 [Task] Follow up permission restructure
  public/js/pimcore/settings/user/role/settings.js
  src/Controller/Admin/UserController.php
  translations/admin.en.yaml
Labels: Task

#74 [Task] Fix installer
  config/services.yaml
  src/Installer.php
  src/PimcoreAdminBundle.php
Labels: Task

#66 Remove personalization editable code
  src/Controller/Admin/Document/DocumentControllerBase.php
Labels: Bug

#78 Fix image upload for users in admin ui
  src/Controller/Admin/UserController.php
Labels: Bug

#75 [Bug] Classification Store - Call to undefined function
  src/Controller/Admin/DataObject/ClassificationstoreController.php
Labels: Bug

#77 [Task] Removed html sanitizer
  public/js/pimcore/element/helpers/gridColumnConfig.js
  public/js/pimcore/helpers.js
  public/js/pimcore/object/gridcolumn/operator/Alias.js
  public/js/pimcore/object/gridcolumn/operator/Anonymizer.js
  public/js/pimcore/object/gridcolumn/operator/AnyGetter.js
  public/js/pimcore/object/gridcolumn/operator/Arithmetic.js
  public/js/pimcore/object/gridcolumn/operator/AssetMetadataGetter.js
  public/js/pimcore/object/gridcolumn/operator/Base64.js
  public/js/pimcore/object/gridcolumn/operator/Boolean.js
  public/js/pimcore/object/gridcolumn/operator/BooleanFormatter.js
  public/js/pimcore/object/gridcolumn/operator/CaseConverter.js
  public/js/pimcore/object/gridcolumn/operator/CharCounter.js
  public/js/pimcore/object/gridcolumn/operator/Concatenator.js
  public/js/pimcore/object/gridcolumn/operator/DateFormatter.js
  public/js/pimcore/object/gridcolumn/operator/ElementCounter.js
  public/js/pimcore/object/gridcolumn/operator/FieldCollectionGetter.js
  public/js/pimcore/object/gridcolumn/operator/GeopointRenderer.js
  public/js/pimcore/object/gridcolumn/operator/HotspotimageRenderer.js
  public/js/pimcore/object/gridcolumn/operator/ImageRenderer.js
  public/js/pimcore/object/gridcolumn/operator/IsEqual.js
  public/js/pimcore/object/gridcolumn/operator/Iterator.js
  public/js/pimcore/object/gridcolumn/operator/JSON.js
  public/js/pimcore/object/gridcolumn/operator/LFExpander.js
  public/js/pimcore/object/gridcolumn/operator/LocaleSwitcher.js
  public/js/pimcore/object/gridcolumn/operator/Merge.js
  public/js/pimcore/object/gridcolumn/operator/ObjectFieldGetter.js
  public/js/pimcore/object/gridcolumn/operator/PHP.js
  public/js/pimcore/object/gridcolumn/operator/PHPCode.js
  public/js/pimcore/object/gridcolumn/operator/PropertyGetter.js
  public/js/pimcore/object/gridcolumn/operator/RequiredBy.js
  public/js/pimcore/object/gridcolumn/operator/StringContains.js
  public/js/pimcore/object/gridcolumn/operator/StringReplace.js
  public/js/pimcore/object/gridcolumn/operator/Substring.js
  public/js/pimcore/object/gridcolumn/operator/Text.js
  public/js/pimcore/object/gridcolumn/operator/TranslateValue.js
  public/js/pimcore/object/gridcolumn/operator/Trimmer.js
  public/js/pimcore/object/gridcolumn/operator/WorkflowState.js
  public/js/pimcore/object/quantityvalue/unitsettings.js
  public/js/pimcore/settings/metadata/predefined.js
  public/js/pimcore/settings/properties/predefined.js
  public/js/pimcore/settings/website.js
  src/DataObject/GridColumnConfig/Operator/AbstractOperator.php
  src/DataObject/GridColumnConfig/Operator/AnyGetter.php
Labels: Task

#76 [Bug][Pimcore 11] User cannot update own password
  public/js/pimcore/settings/profile/panel.js
  src/Controller/Admin/UserController.php
  translations/admin.en.yaml
Labels: Bug

#87 Fix objects tree sort method check
  public/js/pimcore/object/tree.js
Labels: Bug

#86 Grid Batch Edit Change To POST
  public/js/pimcore/element/helpers/gridColumnConfig.js
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#83 [Task]: Defer twemoji variants icons
  src/Twig/Extension/AdminExtension.php
  templates/admin/misc/icon_list.html.twig
Labels: Task

#91 [Bug][11]: 400 Bad Request Error if custom_admin_path_identifier is set
  src/EventListener/CsrfProtectionListener.php
Labels: Bug

#92 [Admin][Documents] Fix (un)publishing documents from tree
  public/js/pimcore/document/tree.js
Labels: Bug

#93 Fix loading empty data object class
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#95 [Task]: Improve non-admin update user
  src/Controller/Admin/UserController.php
Labels: Task

#94 [Bug] Fix layout issue for not_editable structuredTable
  public/js/pimcore/object/tags/structuredTable.js
Labels: Bug

#98 POEditor translations import
  translations/admin.cs.yaml
  translations/admin.de.yaml
  translations/admin.es.yaml
  translations/admin.fr.yaml
  translations/admin.hu.yaml
  translations/admin.it.yaml
  translations/admin.ja.yaml
  translations/admin.nl.yaml
  translations/admin.pl.yaml
  translations/admin.pt.yaml
  translations/admin.pt_br.yaml
  translations/admin.ru.yaml
  translations/admin.sv.yaml
  translations/admin.th.yaml
  translations/admin.tr.yaml
  translations/admin.uk.yaml
  translations/admin.zh_Hans.yaml
  translations/admin_ext.cs.yaml
  translations/admin_ext.de.yaml
  translations/admin_ext.es.yaml
  translations/admin_ext.fr.yaml
  translations/admin_ext.hu.yaml
  translations/admin_ext.it.yaml
  translations/admin_ext.nl.yaml
  translations/admin_ext.pl.yaml
  translations/admin_ext.sk.yaml
  translations/admin_ext.th.yaml
Labels: Task

#100 🔄 synced file(s) with pimcore/sync-common-files
  .gitattributes
Labels: sync

#101 Run actions against stable releases
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  composer.json
Labels: Task

#103 [Bug]: Quantity Value list should not be tied to permission
  src/Controller/Admin/DataObject/QuantityValueController.php
Labels: Bug

#106 [LogoutListener] Fix getting current user from the session
  src/Security/Event/LogoutListener.php
Labels: Bug

#108 [Task] Adapt url slug changes from core
  public/js/pimcore/object/tags/urlSlug.js
  translations/admin.en.yaml
Labels: Task

#111 [Bug]: min value and max value should consider decimal precision
  public/js/pimcore/object/classes/data/numeric.js
Labels: Bug
