Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-06, with the labels that each got.

#114 [Task] Added the classId to panel data
  public/js/pimcore/object/classes/class.js
Labels: Task

#119 [Bug]: Limit for Classificationstore doesn't work with inheritance
  public/js/pimcore/object/tags/classificationstore.js
Labels: Bug

#120 [Bug]: Fix video player being reinitialized on fullscreen
  public/js/pimcore/asset/video.js
Labels: Bug

#130 [Bug] Type fix
  src/EventListener/AdminExceptionListener.php
Labels: Bug

#121 [Task]: Improve Admin translation and application logger sorting
  src/Controller/Admin/TranslationController.php
  src/Helper/QueryParams.php
Labels: Task

#84 Fix grid filters (#15074)
  public/js/pimcore/object/helpers/grid.js
Labels: Bug

#128 [Improvement] Added class to `tabBar`
  public/css/admin.css
  public/js/pimcore/asset/archive.js
  public/js/pimcore/asset/audio.js
  public/js/pimcore/asset/document.js
  public/js/pimcore/asset/folder.js
  public/js/pimcore/asset/image.js
  public/js/pimcore/asset/text.js
  public/js/pimcore/asset/unknown.js
  public/js/pimcore/asset/video.js
  public/js/pimcore/document/email.js
  public/js/pimcore/document/folder.js
  public/js/pimcore/document/hardlink.js
  public/js/pimcore/document/link.js
  public/js/pimcore/document/page.js
  public/js/pimcore/document/snippet.js
  public/js/pimcore/helpers.js
  public/js/pimcore/object/folder.js
  public/js/pimcore/object/object.js
Labels: Improvement

#131 [Improvement]: Introduce `pimcore.events.prepareAffectedNodes`
  public/js/pimcore/elementservice.js
  public/js/pimcore/events.js
Labels: Improvement

#139 [Bug]: Classificationstore inherited key to watch doens't work
  public/js/pimcore/object/tags/classificationstore.js
  public/js/pimcore/object/tags/localizedfields.js
Labels: Bug
