Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-08, with the labels that each got.

#195 Feature/update login screen background
  public/img/login/pc11.svg
  public/img/login/pcx.svg
  templates/admin/login/layout.html.twig
Labels: Bug, Task

#173 Fix broken link to maintenance job documentation
  public/js/pimcore/layout/toolbar.js
Labels: Bug

#199 [Sites] Do not throw exception on missing documents permission when l…
  src/Controller/Admin/DataObject/ClassController.php
  src/Controller/Admin/SettingsController.php
Labels: Bug

#177 Fix deprecation in asset/document tree
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/Document/DocumentController.php
  src/Helper/GridHelperService.php
Labels: Bug

#189 Fix: Create WebsiteSetting without a siteId and a language
  composer.json
  public/js/pimcore/settings/website.js
Labels: Bug

#193 Update ext-modifications.css
  public/css/ext-modifications.css
Labels: Bug

#198 Fix username is set to unkown when userOwner of userModification is null
  src/Controller/Traits/UserNameTrait.php
Labels: Bug

#204 Cast to correct type in grid view
  src/Controller/Admin/DataObject/DataObjectActionsTrait.php
  src/Model/GridConfig/Listing/Dao.php
Labels: Bug

#201 [Bug] Adjust rename function
  public/js/pimcore/asset/tree.js
  public/js/pimcore/document/tree.js
  public/js/pimcore/object/tree.js
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#196 [Grid] Batch update of localized object brick fields always updates English value
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#205 Re-add getTreeNodeConfig support for documents
  src/Service/ElementService.php
Labels: Task

#206 [Bug]: Fix text selection support on disabled field text
  public/css/ext-modifications.css
Labels: Bug

#208 Update DataObjectActionsTrait.php
  src/Controller/Admin/DataObject/DataObjectActionsTrait.php
Labels: Bug

#210 [Bug] Fix Open Street Maps Ajax Error
  public/js/pimcore/helpers.js
  public/js/pimcore/object/tags/geo/abstract.js
  public/js/pimcore/object/tags/geopoint.js
Labels: Bug

#214 Add translation for label in workflow
  src/Controller/Admin/WorkflowController.php
Labels: Bug

#216 Fix forgotten password cannot be reset
  src/Security/Authenticator/AdminTokenAuthenticator.php
Labels: Bug

#219 Asset Helper Controller: get-batch-jobs action - Method not allowed
  src/Controller/Admin/Asset/AssetHelperController.php
Labels: Bug

#191 Support text selection / clickable UI for readonly objectbrick fields
  public/css/ext-modifications.css
  public/js/pimcore/object/tags/objectbricks.js
Labels: Bug

#221 Preview: Missing translations
  translations/admin.en.yaml
Labels: Bug

#220 Fix PIMCORE_CONFIGURATION_DIRECTORY config - …
  composer.json
  src/DependencyInjection/Configuration.php
Labels: Bug

#160 Open object with incompatible latest version
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#222 ExtJSCommand: Don't override $defaultName property
  src/Command/ExtJSCommand.php
Labels: Bug

#232 Content-Security-Policy error on login page
  templates/admin/login/login.html.twig
Labels: Bug

#240 Fix issue with setting the read target to settings-store for Appearance and branding
  src/System/AdminConfig.php
Labels: Bug

#236 Fix getDefaultKeyBindings when no user is passed
  src/Helper/User.php
Labels: Bug

#242 Fix Error 414 | Request-URI Too Large URL: /admin/object/get-select-o…
  public/js/pimcore/object/tags/multiselect.js
  public/js/pimcore/object/tags/select.js
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#224 [Thumbnails] Fix download thumbnails action to use auto formats
  src/Controller/Admin/Asset/AssetController.php
Labels: Bug

#247 Question mark of "Forgot your password" should be in the translation
  templates/admin/login/login.html.twig
  translations/admin.en.yaml
Labels: Bug
