Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-11, with the labels that each got.

#314 Focal Point Marker vanishes on resize
  public/js/pimcore/asset/image.js
Labels: Bug

#296 [Workflows] Fix workflowTransitionHandler not considering global actions
  public/js/pimcore/elementservice.js
Labels: Bug

#329 fix wysiwyg editor init var
  public/js/pimcore/startup.js
Labels: Bug

#330 [Documents] Link - encode full path
  public/js/pimcore/document/editables/link.js
Labels: Bug

#331 [Assets]: Fix focal point position on screen resize and add button to remove focal point
  public/css/icons.css
  public/js/pimcore/asset/image.js
  translations/admin.en.yaml
Labels: Bug

#335 Fix: Grid export results in error when inheritance is disabled
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#333 [Bug]: Fixes DataObject global language selector not working
  public/js/pimcore/object/tags/localizedfields.js
Labels: Bug

#323 [Fix] - Fix problem with filtering action on a non-editable checkbox in the grid
  public/js/pimcore/object/tags/checkbox.js
Labels: Bug

#342 [DataObject] Grid Export - Catch unable to read file exception
  src/Controller/Admin/Asset/AssetHelperController.php
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#340 [Bug]: Fix refresh `Embedded meta info` on replace asset
  src/Controller/Admin/Asset/AssetController.php
Labels: Bug

#344 POEditor translations import
  translations/admin.es.yaml
  translations/admin.fr.yaml
Labels: Task

#345 Fix 2FA authentication for firewalls other than admin
  src/Security/PimcoreUserTwoFactorCondition.php
Labels: Bug

#302 [Improvement]: Add the possibility to select type for Calculated Values
  public/js/pimcore/object/classes/data/calculatedValue.js
  public/js/pimcore/object/tags/calculatedValue.js
Labels: Improvement

#347 [Bug] Avoid multiple save ajax calls
  public/js/pimcore/asset/asset.js
  public/js/pimcore/document/document.js
  public/js/pimcore/element/abstract.js
  public/js/pimcore/object/object.js
Labels: Bug

#354 [Bug]: Download assets issue
  src/Controller/Admin/Asset/AssetController.php
Labels: Bug

#349 POEditor translations import
  translations/admin.ca.yaml
  translations/admin.cs.yaml
  translations/admin.de.yaml
  translations/admin.es.yaml
  translations/admin.fr.yaml
  translations/admin.hu.yaml
  translations/admin.it.yaml
  translations/admin.ja.yaml
  translations/admin.nl.yaml
  translations/admin.pl.yaml
  translations/admin.pt.yaml
  translations/admin.pt_br.yaml
  translations/admin.ru.yaml
  translations/admin.sv.yaml
  translations/admin.th.yaml
  translations/admin.tr.yaml
  translations/admin.uk.yaml
  translations/admin.zh_Hans.yaml
  translations/admin_ext.ca.yaml
  translations/admin_ext.cs.yaml
  translations/admin_ext.de.yaml
  translations/admin_ext.es.yaml
  translations/admin_ext.fr.yaml
  translations/admin_ext.hu.yaml
  translations/admin_ext.it.yaml
  translations/admin_ext.nl.yaml
  translations/admin_ext.pl.yaml
  translations/admin_ext.pt_br.yaml
  translations/admin_ext.ro.yaml
  translations/admin_ext.sk.yaml
  translations/admin_ext.sv.yaml
  translations/admin_ext.th.yaml
  translations/admin_ext.zh_Hans.yaml
Labels: Task

#339 Fix: Use LocaleServiceInterface instead LocaleService
  src/Controller/Admin/Document/PageController.php
  src/DataObject/GridColumnConfig/Operator/LFExpander.php
  src/DataObject/GridColumnConfig/Operator/LocaleSwitcher.php
  src/DataObject/GridColumnConfig/Value/AbstractValue.php
  src/DataObject/GridColumnConfig/Value/DefaultValue.php
  src/DataObject/GridColumnConfig/Value/Factory/DefaultValueFactory.php
Labels: Bug

#356 PSDP-244 UX/UI improvements
  public/css/icons.css
  public/img/avatar.png
  public/img/flat-white-icons/profile.svg
  public/js/pimcore/asset/archive.js
  public/js/pimcore/asset/asset.js
  public/js/pimcore/asset/folder.js
  public/js/pimcore/asset/unknown.js
  public/js/pimcore/document/document.js
  public/js/pimcore/document/email.js
  public/js/pimcore/document/folder.js
  public/js/pimcore/document/hardlink.js
  public/js/pimcore/document/link.js
  public/js/pimcore/document/page.js
  public/js/pimcore/document/page_snippet.js
  public/js/pimcore/element/abstract.js
  public/js/pimcore/helpers.js
  public/js/pimcore/layout/toolbar.js
  public/js/pimcore/object/folder.js
  public/js/pimcore/object/object.js
  public/js/pimcore/startup.js
  src/Controller/Admin/IndexController.php
  src/Event/IndexActionSettingsEvent.php
  templates/admin/index/index.html.twig
  translations/admin.en.yaml
Labels: Improvement

#355 [Task]: Deprecate date editable format fallback
  public/js/pimcore/document/editables/date.js
Labels: Task

#360 [Assets] Metadata - Fix xlsx/csv-export does not work
  public/js/pimcore/asset/gridexport/csv.js
  public/js/pimcore/asset/gridexport/xlsx.js
  public/js/pimcore/object/gridexport/csv.js
  public/js/pimcore/object/gridexport/xlsx.js
  src/Controller/Admin/Asset/AssetHelperController.php
  translations/admin.en.yaml
Labels: Bug
