Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-12, with the labels that each got.

#364 [Bug]: Relation field wrong dirty detector and "losing" data even without any changes
  public/js/pimcore/asset/metadata/grid.js
  public/js/pimcore/element/helpers/gridCellEditor.js
Labels: Bug

#357 [Bug] Key 32 translated to Space
  public/js/pimcore/settings/user/user/keyBindings.js
Labels: Bug

#367 Fix: stan errors
  src/Controller/Admin/WorkflowController.php
  src/Service/Workflow/ActionsButtonService.php
Labels: Bug

#362 Password reset - fix for possible host header injection
  src/Controller/Admin/LoginController.php
Labels: Bug, Security

#368 Fix phpstan
  composer.json
Labels: Task

#370 [localized fields] translate tooltip
  public/js/pimcore/object/tags/localizedfields.js
Labels: Task

#373 Fix: CSP for worker
  src/Security/ContentSecurityPolicyHandler.php
Labels: Bug

#371 Fix: Default data in pimcore_table are not applied
  public/js/pimcore/document/editables/table.js
Labels: Bug
