Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2023-07, with the labels that each got.

#150 Fix: 500 error when opening grid
  src/Model/GridConfig/Listing/Dao.php
Labels: Bug

#143 Service::copyAsChild() - $language param should be a string or null
  composer.json
  src/Controller/Admin/Document/DocumentController.php
Labels: Bug

#147 Fix xss in admin login 2fa setup page
  templates/admin/login/two_factor_setup.html.twig
Labels: Security

#145 Don't use session if request is stateless
  src/EventListener/AdminSessionBagListener.php
Labels: Bug

#158 [Bug] Reload button doesn't work
  public/js/pimcore/asset/archive.js
  public/js/pimcore/asset/audio.js
  public/js/pimcore/asset/document.js
  public/js/pimcore/asset/folder.js
  public/js/pimcore/asset/image.js
  public/js/pimcore/asset/text.js
  public/js/pimcore/asset/unknown.js
  public/js/pimcore/asset/video.js
  public/js/pimcore/document/email.js
  public/js/pimcore/document/folder.js
  public/js/pimcore/document/hardlink.js
  public/js/pimcore/document/link.js
  public/js/pimcore/document/page.js
  public/js/pimcore/document/snippet.js
  public/js/pimcore/object/folder.js
  public/js/pimcore/object/object.js
Labels: Bug

#164 [Bug]: Fix path to filetype not supported
  src/Command/ExtJSCommand.php
  src/Controller/Admin/Asset/AssetController.php
Labels: Bug

#165 [Task]: Add missing slash
  src/Command/ExtJSCommand.php
Labels: Task

#159 [Codeception] Use lowest dependencies for db
  .github/workflows/codeception.yml
Labels: Improvement

#168 [Bug][DataObject][Grid] Cannot filter for system columns path & key
  src/Helper/GridHelperService.php
Labels: Bug

#171 Fix: Error when copying document (Invalid language: false)
  public/js/pimcore/document/tree.js
  src/Controller/Admin/Document/DocumentController.php
Labels: Bug

#176 Fix Inconsistent Marshaling in Session Storage Handling
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#180 Confidential information provided to user with no permissions
  public/js/pimcore/startup.js
  src/Controller/Admin/DataObject/ClassController.php
  src/Controller/Admin/IndexController.php
  src/Controller/Admin/SettingsController.php
Labels: Security

#174 Make BundleManagerEvents extend from \Pimcore\Event\BundleManagerEvents
  composer.json
  src/Event/BundleManagerEvents.php
Labels: Bug

#183 [Bug]: Translations transforms special characters, empty html not actually empty due TinyMCE
  public/js/pimcore/settings/translation.js
  public/js/pimcore/settings/translationEditor.js
Labels: Bug
