Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-04, with the labels that each got.

#452 Add translations for missing keys in classification store.
  translations/admin_ext.en.yaml
Labels: Pimcore:ToDo

#436 Provide fieldname to get-nice-path calls in grid editor
  public/js/pimcore/element/helpers/gridCellEditor.js
Labels: Pimcore:ToDo

#482 Update cla checker
  .github/workflows/cla.yml
Labels: Task

#477 Revert part of PSDP-244/686e913 to fix an error when uploading a new avatar
  public/js/pimcore/helpers.js
Labels: Bug

#478 [Bug]: UI Inconsistencies between Advanced Many-to-Many and Many-to-Many data types
  public/js/pimcore/object/tags/abstractRelations.js
  public/js/pimcore/object/tags/advancedManyToManyRelation.js
  public/js/pimcore/object/tags/manyToManyObjectRelation.js
  public/js/pimcore/object/tags/manyToManyRelation.js
  public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Bug

#483 Fix: js error on asset save only scheduled tasks
  public/js/pimcore/asset/asset.js
Labels: Bug

#415 Fix: quantity values-load base units
  public/js/pimcore/object/quantityvalue/unitsettings.js
Labels: Pimcore:ToDo

#446 PHP 8.3 Support
  .github/workflows/codeception.yml
  .github/workflows/static-analysis.yml
  composer.json
Labels: Pimcore:ToDo

#448 Introduce event to handle different object edit lock tasks
  src/Controller/Admin/DataObject/DataObjectController.php
  src/Event/AdminEvents.php
Labels: Pimcore:ToDo

#495 [Bug]: Fix typo and apply CLA changes
  .github/workflows/cla.yml
  public/js/pimcore/object/helpers/selectField.js
Labels: Bug

#453 [Bug]: Fix attributes->get('_controller') potentially being null causing TypeError in UsageStatisticsListener.php
  src/EventListener/UsageStatisticsListener.php
Labels: Pimcore:ToDo

#503 Fix null to property error in operator text
  public/js/pimcore/object/gridcolumn/operator/Text.js
Labels: Bug

#510 [Bug] Mark table field dirty after pasting data from clipboard
  public/js/pimcore/object/tags/table.js
Labels: Bug

#472 Add possibility to make languages not mandatory
  public/js/pimcore/object/helpers/edit.js
  public/js/pimcore/settings/system.js
  src/Controller/Admin/IndexController.php
  src/Controller/Admin/SettingsController.php
  translations/admin_ext.en.yaml
Labels: Pimcore:ToDo

#514 [Task]: Update SECURITY.md
  SECURITY.md
Labels: Task, Pimcore:ToDo

#467 [BUGFIX] Fixed dirty detection of carbon fields
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug, Pimcore:ToDo
