Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-02, with the labels that each got.

#412 Fix: Tag access rights
  src/Controller/Admin/TagsController.php
Labels: Security

#413 [Bug]: Fix grid batch edit not considering the current language
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug, Pimcore:ToDo, Pimcore:Priority

#414 Fix typo in twig variable names
  templates/admin/data_object/data_object/diff_versions.html.twig
Labels: Task

#410 UserNameTrait: Use Required attribute
  src/Controller/Traits/UserNameTrait.php
Labels: Pimcore:ToDo

#392 Fix loading login background image from remote
  src/Controller/Admin/LoginController.php
  src/Twig/Extension/AdminExtension.php
  templates/admin/login/layout.html.twig
Labels: Bug, Pimcore:ToDo

#418 [Bug]: Fix crash when selecting an empty value in Asset Grid multiselect filters
  src/Helper/GridHelperService.php
Labels: Bug

#400 [Task]: Change login background image
  public/img/login/pimconaut2024.jpg
  templates/admin/login/layout.html.twig
Labels: Task, Pimcore:Priority

#382 Support displaying localized fields in field collections in version view
  templates/admin/data_object/data_object/preview_version.html.twig
Labels: Pimcore:ToDo

#430 [Bug]: Grid export error with localized brick
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#428 [Task]: Fix potential host injection in invitation link
  src/Controller/Admin/UserController.php
Labels: Task, Security

#427 [Bug]: Fix unwanted code (hasTargetGroupSpecificEditables) removal in DocumentControllerBase
  src/Controller/Admin/Document/DocumentControllerBase.php
Labels: Bug

#426 [Bug]: Fix grid display of dynamic select options
  public/js/pimcore/object/helpers/grid.js
  public/js/pimcore/object/tags/select.js
Labels: Bug

#419 [Bug]: Fix asset metadata tag type
  public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Bug, Pimcore:ToDo

#417 [Bug]: Activate Filter for Asset grids
  public/js/pimcore/asset/helpers/grid.js
Labels: Bug, Pimcore:ToDo

#137 Many-to-many-relations: support multi-file-upload
  public/js/pimcore/helpers.js
  translations/admin.en.yaml
Labels: Improvement, Pimcore:Priority
