Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-07, with the labels that each got.

#527 Fix: Add video service providers to CSP allow list
  src/Security/ContentSecurityPolicyHandler.php
Labels: Pimcore:ToDo

#437 Fix csrf token generation in LoginController::loginAction
  src/Controller/Admin/LoginController.php
Labels: Pimcore:ToDo

#594 Add branch alias
  composer.json
Labels: Task

#601 Change pimcore/pimcore requirements to allow future core versions
  composer.json
Labels: Task

#605 [Bug]: Fix Master Admin mode does not work for Field collection
  public/js/pimcore/object/tags/fieldcollections.js
Labels: Bug

#616 Fix nice path support inheritance
  src/Controller/Admin/ElementController.php
Labels: Bug

#622 Bug document Save Buttons
  public/js/pimcore/document/document.js
  public/js/pimcore/document/page_snippet.js
Labels: Bug

#625 [Security]: Disclosed system and database information behind /admin firewall via statistics
  config/services.yaml
  public/js/pimcore/startup.js
  src/Controller/Admin/IndexController.php
Labels: Security

#629 [Task]: Optmize tags treeGetChildrenByIdAction
  src/Controller/Admin/TagsController.php
Labels: Task, Pimcore:ToDo

#635 [PIMCORE-17387] Fix bug with reorder of localized fields in class
  public/js/pimcore/object/helpers/layout.js
Labels: Pimcore:ToDo

#631 Update branch alias
  composer.json
Labels: Pimcore:ToDo

#550 Improve logic for classification store in diff_versions in data objects
  templates/admin/data_object/data_object/diff_versions.html.twig
Labels: Pimcore:ToDo

#389 [Improvement] Case insensitive search for object title and key in filter grid view
  src/Helper/GridHelperService.php
Labels: Improvement, Pimcore:ToDo

#624 Add missing workflow_transition_unsaved_data string
  translations/admin.en.yaml
Labels: Task, Pimcore:ToDo
