Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-01, with the labels that each got.

#391 [bugfix] Do not call htmlspecialchars with null
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/DataObject/ClassController.php
  src/Controller/Admin/DataObject/ClassificationstoreController.php
  src/Service/ElementService.php
Labels: Bug

#387 [Improvement] Adding post menu build event
  public/js/pimcore/events.js
  public/js/pimcore/layout/toolbar.js
Labels: Improvement

#378 Fix broken image editor
  templates/admin/asset/image_editor.html.twig
Labels: Bug

#395 [BUG, EC] Rendering of localized classification store is slow in backend for many languages
  public/js/pimcore/object/tags/classificationstore.js
Labels: Bug, Pimcore: Priority

#393 Refactor export handler from inline into own function
  public/js/pimcore/object/helpers/gridTabAbstract.js
Labels: Improvement

#377 [TinyMCE] FIx empty content not being empty due innerHtml
  composer.json
  public/js/pimcore/document/edit.js
  public/js/pimcore/object/edit.js
  public/js/pimcore/settings/translationEditor.js
Labels: Task

#383 [Bug]: Fix return type of parseLogginParamObject
  src/Controller/Admin/EmailController.php
Labels: Bug

#399 Tree shows Root for all names
  src/Controller/Traits/AdminStyleTrait.php
Labels: Bug

#375 [Bug]: Removes `Filter by relation` from reverse object relation grid view
  public/js/pimcore/object/tags/reverseObjectRelation.js
Labels: Bug

#405 [Bug] Add quote for ids in Admin download files as zip
  src/Controller/Admin/Asset/AssetController.php
Labels: Bug, Security

#403 [Task]: Small performance improvement in object grid
  src/Controller/Admin/DataObject/DataObjectActionsTrait.php
Labels: Task, Pimcore:ToDo

#369 Fix: direction when sorting DESC
  public/js/pimcore/treenodelocator.js
Labels: Bug, Pimcore:ToDo

#386 Support QuantityValueRange on Classification Store as mentioned in #385
  public/js/pimcore/object/classes/data/quantityValueRange.js
Labels: Improvement, Pimcore:ToDo

#372 Fix: gridview filtering with multiple filters starting with null or empty filter
  src/Helper/GridHelperService.php
Labels: Bug, Pimcore:ToDo
