Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-03, with the labels that each got.

#450 Fix invite user modal translation
  src/Controller/Admin/UserController.php
Labels: Bug

#449 Thumbnail: Don't create cover item with positioning: null
  public/js/pimcore/settings/thumbnail/item.js
Labels: Bug

#451 [Bug]: Split view for localized fields in object bricks not working properly (data loss)
  public/js/pimcore/object/tags/localizedfields.js
Labels: Bug

#454 [Data Objects] Password : Deprecate support for algorithms other than password_hash
  CHANGELOG.md
  public/js/pimcore/object/classes/data/password.js
  src/Controller/Admin/SettingsController.php
Labels: Improvement, Pimcore:ToDo

#458 [Docs]: Removed outdated line about deprecated
  CHANGELOG.md
Labels: Task

#460 Document version conparison fix: make the comparison independent from session/cookie authentication
  config/pimcore/routing.yaml
  src/Controller/Admin/Document/DocumentController.php
  templates/admin/document/document/diff_versions.html.twig
Labels: Bug

#461 Followup #460
  src/Controller/Admin/Document/DocumentController.php
Labels: Task

#423 Added Gotenberg support for creating page and version previews
  composer.json
  src/Controller/Admin/Document/DocumentController.php
  src/Controller/Admin/IndexController.php
Labels: Improvement

#465 464 fix filtering objects or variant in grid tab
  public/js/pimcore/object/helpers/gridTabAbstract.js
  src/Helper/GridHelperService.php
  translations/admin.en.yaml
Labels: Improvement, Pimcore:ToDo

#441 Fix label in string contains operator
  public/js/pimcore/object/gridcolumn/operator/StringContains.js
Labels: Pimcore:ToDo

#404 Add translation for invalid option in multiselect / select
  translations/admin.de.yaml
  translations/admin.en.yaml
Labels: Pimcore:ToDo

#411 Fix: Upload dialog of the object video tag
  public/js/pimcore/object/tags/video.js
Labels: Pimcore:ToDo

#455 Hide buttons for not editable tables
  public/js/pimcore/object/tags/table.js
Labels: Pimcore:ToDo

#471 Only run POEditor Export in main repository not in forks
  .github/workflows/poeditor-export.yaml
Labels: Improvement, Pimcore:ToDo

#439 Don't use 100% width for grid/cell editor
  public/js/pimcore/asset/metadata/tags/abstract.js
  public/js/pimcore/asset/metadata/tags/input.js
  public/js/pimcore/asset/metadata/tags/select.js
  public/js/pimcore/asset/metadata/tags/textarea.js
  public/js/pimcore/object/helpers/grid.js
  public/js/pimcore/object/tags/abstract.js
  public/js/pimcore/object/tags/booleanSelect.js
  public/js/pimcore/object/tags/input.js
  public/js/pimcore/object/tags/numeric.js
  public/js/pimcore/object/tags/rgbaColor.js
  public/js/pimcore/object/tags/select.js
  public/js/pimcore/object/tags/textarea.js
  public/js/pimcore/object/tags/urlSlug.js
  public/js/pimcore/object/tags/wysiwyg.js
Labels: Pimcore:ToDo

#438 🔄 synced file(s) with pimcore/sync-common-files
  .github/ci/files/.env
Labels: sync

#469 [BUGFIX]: Moving objects in alphabetical tree
  public/js/pimcore/object/tree.js
Labels: Bug, Pimcore:ToDo
