Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-12, with the labels that each got.

#755 Improvement: Add wysiwyg textarea id to drop event
  public/js/pimcore/document/editables/wysiwyg.js
  public/js/pimcore/object/tags/wysiwyg.js
  public/js/pimcore/settings/translationEditor.js
Labels: Improvement, Pimcore:ToDo

#786 [Task]: Followup #767 Grid permissions
  src/Helper/GridHelperService.php
Labels: Bug, Pimcore:Priority

#782 Revert "Fix formatting for alias on relations (#745)"
  src/DataObject/GridColumnConfig/Value/DefaultValue.php
Labels: Bug

#788 [Bug] Cslanguage can be null
  src/DataObject/GridColumnConfig/Value/DefaultValue.php
Labels: Bug

#746 Add Operator to Read the Newest Version of an Object
  .github/ci/files/config/export.yaml
  config/export.yaml
  public/js/pimcore/object/gridcolumn/operator/VersionGetter.js
  src/DataObject/GridColumnConfig/Operator/VersionGetter.php
  templates/admin/index/index.html.twig
Labels: Pimcore:ToDo

#725 Fix Asset exists check for files within folders when drag and dropping.
  public/js/pimcore/asset/tree.js
  src/Controller/Admin/Asset/AssetController.php
Labels: Pimcore:ToDo

#794 [Bug] Fix faulty slash in condition
  src/Helper/GridHelperService.php
Labels: Bug

#785 Fix: Video Element not working
  public/js/pimcore/document/editables/video.js
Labels: Pimcore:ToDo

#798 [Bug] Fixed permission checks in certain constellations
  src/Helper/GridHelperService.php
Labels: Bug

#793 [BUG] fix permission check in GridHelperService for wrong query column if type is asset
  src/Helper/GridHelperService.php
Labels: Pimcore:ToDo

#799 [Task] optimize permission concat
  src/Helper/GridHelperService.php
Labels: Task

#802 Update error modal to handle timedout.
  public/js/pimcore/startup.js
Labels: Improvement

#803 Handle mime-type as system column.
  public/js/pimcore/asset/helpers/grid.js
  src/Service/GridData/Asset.php
Labels: New Feature
