Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2024-06, with the labels that each got.

#542 Decouple simple backend search from admin UI classic bundle
  src/Event/AdminEvents.php
  src/Helper/GridHelperService.php
  tests/Model/GridHelper/GridHelperTest.php
Labels: Improvement, Pimcore:ToDo

#557 Fix edit in grid for date fields with date column type
  public/js/pimcore/object/tags/date.js
Labels: Bug

#565 Fix date attributes without timezone support when server timezone is configured
  public/js/pimcore/functions.js
  public/js/pimcore/object/tags/date.js
  public/js/pimcore/object/tags/datetime.js
Labels: Bug

#561 [Bug]: Fix Quantity Value Range turning 0 into empty/null
  public/js/pimcore/object/tags/quantityValueRange.js
Labels: Bug, Pimcore:ToDo

#558 Fix issue with "Undefined array key 0" when bulk importing custom layouts
  src/Controller/Admin/DataObject/ClassController.php
Labels: Pimcore:ToDo

#545 FieldDefinition: Add missing forbidden names
  public/js/pimcore/object/classes/data/data.js
  public/js/pimcore/object/fieldcollection.js
  public/js/pimcore/object/objectbrick.js
Labels: Bug, Pimcore:ToDo

#292 Make global language switch affect classification store
  public/js/pimcore/object/tags/classificationstore.js
Labels: Improvement, Pimcore:ToDo, Pimcore:Priority

#567 [Improvement] Split icon library
  CHANGELOG.md
  public/js/pimcore/iconlibrary.js
  public/js/pimcore/layout/toolbar.js
  public/js/pimcore/object/classes/class.js
  public/js/pimcore/object/classes/layout/layout.js
  src/Controller/Admin/DataObject/ClassController.php
  src/Controller/Admin/MiscController.php
  src/Tool.php
  src/Twig/Extension/AdminExtension.php
  templates/admin/index/index.html.twig
  templates/admin/misc/icon_list.html.twig
  translations/admin_ext.en.yaml
Labels: Improvement

#462 [Bug] JS Errors on Bricks with many-to-many relation and specific configuration
  public/js/pimcore/helpers.js
  public/js/pimcore/object/helpers/layout.js
Labels: Bug, Pimcore:ToDo

#549 [Improvement]: Make Dependencies tab hideable via config
  public/js/pimcore/asset/archive.js
  public/js/pimcore/asset/audio.js
  public/js/pimcore/asset/document.js
  public/js/pimcore/asset/folder.js
  public/js/pimcore/asset/image.js
  public/js/pimcore/asset/text.js
  public/js/pimcore/asset/unknown.js
  public/js/pimcore/asset/video.js
  public/js/pimcore/document/email.js
  public/js/pimcore/document/folder.js
  public/js/pimcore/document/hardlink.js
  public/js/pimcore/document/link.js
  public/js/pimcore/document/page.js
  public/js/pimcore/document/snippet.js
  public/js/pimcore/object/folder.js
  public/js/pimcore/object/object.js
  src/Controller/Admin/IndexController.php
Labels: Pimcore:ToDo

#457 [Improvement]: Move grid data related functions from pimcore/pimcore v11.3
  composer.json
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/DataObject/DataObjectActionsTrait.php
  src/Controller/Admin/DataObject/DataObjectHelperController.php
  src/GDPR/DataProvider/Assets.php
  src/GDPR/DataProvider/DataObjects.php
  src/Service/GridData/Asset.php
  src/Service/GridData/DataObject.php
  src/Service/GridData/Document.php
  src/Service/GridData/Element.php
Labels: Improvement, Pimcore:ToDo, Pimcore:Priority

#447 Remove "Default-Language in Admin-Interface"
  .github/ci/files/config/system.yaml
  CHANGELOG.md
  public/js/pimcore/settings/system.js
  translations/admin_ext.en.yaml
Labels: Pimcore:ToDo

#571 [Task]: Remove some leftover of unwanted change
  public/js/pimcore/object/versions.js
  public/js/pimcore/settings/profile/panel.js
Labels: Task

#548 Respect the user's timezone in the version preview and in CSV exports
  public/js/pimcore/asset/versions.js
  public/js/pimcore/element/helpers/gridColumnConfig.js
  public/js/pimcore/functions.js
  public/js/pimcore/object/versions.js
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/DataObject/DataObjectController.php
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug, Pimcore:ToDo

#573 [Bug]: Fix potential bug in grid view options
  src/Controller/Admin/DataObject/ClassController.php
Labels: Bug, Pimcore:ToDo

#578 Remove STAN check because of changes in 11.x
  .github/workflows/static-analysis.yml
Labels: Task

#566 Field type Table: Support autoSize columns
  public/js/pimcore/object/tags/table.js
Labels: Pimcore:ToDo

#582 Split icon library follow up
  public/js/pimcore/iconlibrary.js
  public/js/pimcore/object/classes/class.js
  src/Controller/Admin/DataObject/ClassController.php
  src/Controller/Admin/MiscController.php
  templates/admin/misc/icon_library_reload.html.twig
Labels: Bug

#583 Date/datetime timezone related fixes
  public/js/pimcore/functions.js
  public/js/pimcore/object/tags/date.js
  public/js/pimcore/object/tags/datetime.js
  translations/admin.en.yaml
Labels: Bug

#585 Hide variant filter when variants are disabled
  public/js/pimcore/object/helpers/gridTabAbstract.js
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#587 Fix date format parsing in scheduler when localized date format is enabled
  public/js/pimcore/element/scheduler.js
Labels: Bug

#589 Grid options preview wrong date/time format
  public/js/pimcore/object/tags/date.js
  public/js/pimcore/object/tags/datetime.js
Labels: Bug

#590 Respect user timezone for creation/modification dates in version previews
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#579 Check if searchField is present
  public/js/pimcore/object/folder/search.js
Labels: Bug

#536 [BUG] remove checks on quantity value convert actions
  src/Controller/Admin/DataObject/QuantityValueController.php
Labels: Pimcore:ToDo
