Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2025-01, with the labels that each got.

#807 [Bug]: "Preview not available: PDF is being scanned" after update to 11.1.2
  src/Controller/Admin/Asset/AssetController.php
  templates/admin/asset/get_preview_pdf_open_in_new_tab.html.twig
  templates/admin/asset/show_version_unknown.html.twig
  translations/admin.en.yaml
Labels: Bug

#808 [Security]: Avoid user enumeration via reset password link
  src/Controller/Admin/LoginController.php
  templates/admin/login/lost_password.html.twig
Labels: Task, Security

#804 Fix asset preview performance
  src/Controller/Admin/Asset/AssetController.php
  src/Helper/GridHelperService.php
Labels: Pimcore:ToDo

#814 Fix link to Pimcore docs
  public/js/pimcore/settings/translation.js
Labels: Bug

#817 [Bug]: Fix potential leak when exporting
  src/Controller/Admin/Asset/AssetHelperController.php
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#806 [Bug]: Add the error details on Asset update problem
  public/js/pimcore/elementservice.js
Labels: Bug, Pimcore:ToDo
