Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2025-04, with the labels that each got.

#731 BUG: display the nice path if field type combo is not editable
  public/js/pimcore/object/tags/manyToOneRelation.js
Labels: Pimcore:ToDo

#892 [Bug]: Fix typecast Tags::getById
  src/Helper/GridHelperService.php
Labels: Task

#895 Fix Service::addTreeFilterJoins(): Argument #1 ($cv) must be of type …
  src/Controller/Admin/DataObject/DataObjectController.php
Labels: Bug

#900 [Bug]: Fix nullable searchType
  src/Controller/Admin/DataObject/DataObjectHelperController.php
Labels: Bug

#898 [Feature]: Allow using same type of objectbrick more than once on a data object
  public/js/pimcore/object/objectbricks/field.js
  src/Controller/Admin/DataObject/ClassController.php
Labels: New Feature, Pimcore:ToDo

#912 Add Product Registration
  .github/ci/files/config/packages/test/config.yaml
Labels: Task

#913 Fix codeception
  .github/workflows/codeception.yaml
Labels: Task

#916 [Bug] Grid filtering for ID does not work
  src/Helper/GridHelperService.php
Labels: Bug
