Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2025-08, with the labels that each got.

#976 Remove unused `database_administration` translation
  translations/admin_ext.en.yaml
Labels: Task, Pimcore:ToDo

#966 Fix: wrong check of classname against classid in perspectiveCfg.classes
  public/js/pimcore/object/tree.js
Labels: Bug

#694 Fixes cell width not taking all space
  public/js/pimcore/object/tags/table.js
Labels: Bug, Pimcore:ToDo
