Repository pimcore/admin-ui-classic-bundle, pull requests merged in 2025-03, with the labels that each got.

#759 [Translations] Incorrect translation for separated
  public/js/pimcore/object/helpers/optionEditor.js
  translations/admin.en.yaml
  translations/admin_ext.en.yaml
Labels: Pimcore:ToDo

#851 [Task]: Add phpstan-rules test requirement
  composer.json
  phpstan.neon
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/DataObject/DataObjectController.php
  src/Controller/Admin/Document/DocumentController.php
  src/Controller/Admin/Document/DocumentControllerBase.php
  src/Controller/AdminAbstractController.php
  src/Event/AdminEvents.php
  src/Event/AssetEvents.php
  src/Event/Login/LoginCredentialsEvent.php
  src/Event/Login/LoginFailedEvent.php
  src/Event/Login/LoginRedirectEvent.php
  src/Event/Login/LogoutEvent.php
  src/Event/Login/LostPasswordEvent.php
  src/Event/Model/AssetDeleteInfoEvent.php
  src/Event/Model/DataObjectDeleteInfoEvent.php
  src/Event/Model/DocumentDeleteInfoEvent.php
  src/Event/Model/ElementDeleteInfoEventInterface.php
  src/Event/Traits/ElementDeleteInfoEventTrait.php
  src/Helper/GridHelperService.php
  src/Model/GridConfig/Dao.php
  src/Model/GridConfig/Listing/Dao.php
  src/Model/GridConfigFavourite/Dao.php
  src/Model/GridConfigFavourite/Listing/Dao.php
  src/Model/GridConfigShare/Dao.php
  src/Model/GridConfigShare/Listing/Dao.php
  src/Service/PreviewGenerator.php
Labels: Task

#850 [Bug]: Fix error related to paging and expanded nodes
  public/js/pimcore/overrides.js
Labels: Bug

#849 [Task] Consistently use symfony/mime to get MIME type of assets
  src/Controller/Admin/Asset/AssetController.php
Labels: Task

#820 Allow filtering on Asset metadata.
  public/js/pimcore/element/helpers/gridColumnConfig.js
Labels: Improvement, Pimcore:ToDo

#853 [Bug]: Missing Specific Settings when using FC in custom layouts
  public/js/pimcore/object/classes/data/fieldcollections.js
Labels: Bug

#846 Bug] Disabling name field
  public/js/pimcore/object/classes/data/gender.js
Labels: Bug

#848 Fix deleting sub objects of locked folders if folder is selected
  public/js/pimcore/elementservice.js
  src/Controller/Admin/ElementControllerBase.php
Labels: Bug

#858 add 'empty' option to dynamic selects in grid view
  public/js/pimcore/object/tags/select.js
Labels: Pimcore:ToDo

#863 [translation] fix url-slug datatype info
  translations/admin_ext.en.yaml
Labels: Bug

#862 Timezone: Consistent behavior for PHP and JavaScript
  src/Controller/Admin/IndexController.php
Labels: Bug

#844 [Task] Follow up: Removed deprecated password hashing algorithms
  public/js/pimcore/object/classes/data/password.js
Labels: Task

#864 Limit must be an int
  src/Helper/GridHelperService.php
Labels: Bug, Task, Pimcore:ToDo

#867 Numerous fixes for getById calls
  src/Controller/Admin/Asset/AssetController.php
  src/Controller/Admin/Asset/AssetHelperController.php
  src/Controller/Admin/DataObject/DataObjectController.php
  src/Controller/Admin/Document/DocumentControllerBase.php
  src/Controller/Admin/EmailController.php
Labels: Bug, Pimcore:ToDo

#871 Reverse relation fields: support column filtering
  public/js/pimcore/object/tags/manyToManyObjectRelation.js
  public/js/pimcore/object/tags/reverseObjectRelation.js
Labels: Pimcore:ToDo

#873 Fix: inherited values for classificationstore in grid
  src/Service/GridData/DataObject.php
Labels: Bug

#870 [Improvement]: Add support to DBAL v4
  composer.json
  src/Controller/Admin/Asset/AssetHelperController.php
  src/Controller/Admin/DataObject/ClassificationstoreController.php
  src/Controller/Admin/DataObject/DataObjectHelperController.php
  src/Controller/Admin/Document/DocumentController.php
  src/Controller/Admin/ElementController.php
  src/Controller/Admin/RecyclebinController.php
  src/Helper/GridHelperService.php
  src/Helper/QueryParams.php
  tests/Model/GridHelper/GridHelperTest.php
Labels: Improvement, Pimcore:Priority

#874 Fix: select in reverse relation
  public/js/pimcore/object/tags/reverseObjectRelation.js
Labels: Bug, Pimcore:ToDo

#878 bugfix: hide marker and predefinedDataTemplates from image url, avoid long uris
  public/js/pimcore/document/editables/image.js
Labels: Improvement
